model_list:
  - model_name: Claude 3 Haiku By Anthropic (Served via LiteLLM)
    litellm_params:
      model: anthropic.claude-3-haiku-20240307-v1:0
litellm_settings:
  modify_params: True
  drop_params: true
