model_list:
  - model_name: Claude 3 Haiku By Anthropic (Served via LiteLLM)
    litellm_params:
      model: anthropic.claude-3-haiku-20240307-v1:0
  - model_name: amazon.nova-pro-v1:0 (Served via LiteLLM)
    litellm_params:
      model: bedrock/amazon.nova-pro-v1:0
  - model_name: Claude 3.7 Sonnet By Anthropic (Served via LiteLLM)
    litellm_params:
      model: anthropic.claude-3-7-sonnet-20250219-v1:0
  

litellm_settings:
  modify_params: True
  drop_params: true
